language: scala
scala:
  - 2.12.4
jdk:
  - oraclejdk8

services:
  - docker

env:
  -ROLLER_IMAGE=rpgroller:snapshot

jobs:
  include:
    - stage: unit test
      script: sbt backend/test
    - stage: dockerize
      script:
        - sbt backend/docker:publishLocal
        - docker-compose -f docker/docker-compose.yml build
    - stage: functional tests
      script:
        - cd docker && sh start_application.sh && cd -
        - sbt functional/test
