/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class Statistics (
  weaponSkill: Integer,
  ballisticSkill: Integer,
  strength: Integer,
  toughness: Integer,
  agility: Integer,
  intelligence: Integer,
  perception: Integer,
  willPower: Integer,
  fellowship: Integer,
  influence: Integer
)

